from enum import Enum, auto
class PerceptionState(Enum):
    IDLE = auto()
    CAPTURE_RGBD_FRAME = auto()
    INIT_RTABMAP_BRIDGE = auto()
    ACTIVE_VISION = auto()
    DETECT_VISUAL_MARKERS = auto()
    DETECT_HUMAN = auto()
    DETECT_OBSTACLE = auto()
    DETECT_NEW_OBJECTS = auto()
    TRACK_OBJECTS_KALMAN = auto()
    UPDATE_SLAM_FROM_RTABMAP = auto()
    CHECK_PATH_DEVIATION = auto()
    BUILD_POINT_CLOUD = auto()
    SAVE_POINT_CLOUD_IF_READY = auto()
    PRINT_STATE = auto()
    PUBLISH_ROS2_STATE = auto()
    ERROR = auto()
